//! Dictionary / language model.
//!
//! Reads `data/bopomofo-lm.tsv`, generated by `data/build.mjs` from McBopomofo's
//! MIT-licensed data. Each row is `reading<TAB>word<TAB>log10_probability`.
//!
//! The format is deliberately plain text and is shared byte-for-byte with the
//! TypeScript reference implementation, so the two engines cannot drift apart in
//! what they think the language model says.

use std::collections::{HashMap, HashSet};
use std::fs::File;
use std::io::{BufRead, BufReader};
use std::path::Path;

use crate::syllable::split_reading;

#[derive(Debug, Clone, PartialEq)]
pub struct Entry {
    pub word: String,
    pub score: f64,
    pub reading: String,
    /// number of syllables the word spans
    pub syllables: usize,
}

#[derive(Debug, Clone, Copy)]
pub struct DictionaryOptions {
    /// hard cap on how many syllables one dictionary word may cover
    pub max_word_syllables: usize,
    /// keep at most this many candidates per reading
    pub max_candidates_per_reading: usize,
}

impl Default for DictionaryOptions {
    fn default() -> Self {
        // 200 matches CANDIDATE_CAP in the engine, so the loader is not a
        // second, lower ceiling than the candidate window. It was 128, which
        // stayed invisible while data/build.mjs capped every reading at 100.
        Self { max_word_syllables: 10, max_candidates_per_reading: 200 }
    }
}

#[derive(Debug, Default)]
pub struct Dictionary {
    by_reading: HashMap<String, Vec<Entry>>,
    readings: Vec<String>,
    max_word_syllables: usize,
    size: usize,
}

impl Dictionary {
    pub fn load(path: impl AsRef<Path>) -> std::io::Result<Dictionary> {
        Self::load_with(path, DictionaryOptions::default())
    }

    pub fn load_with(path: impl AsRef<Path>, options: DictionaryOptions) -> std::io::Result<Dictionary> {
        let file = File::open(path)?;
        let mut dict = Dictionary { max_word_syllables: 1, ..Default::default() };
        let mut max_span = 1usize;

        for line in BufReader::new(file).lines() {
            let line = line?;
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            let mut parts = line.splitn(3, '\t');
            let (Some(reading), Some(word), Some(score)) =
                (parts.next(), parts.next(), parts.next())
            else {
                continue;
            };
            let Ok(score) = score.trim().parse::<f64>() else { continue };
            if reading.is_empty() || word.is_empty() {
                continue;
            }
            let syllables = split_reading(reading).len();
            let list = dict.by_reading.entry(reading.to_string()).or_insert_with(|| {
                dict.readings.push(reading.to_string());
                Vec::new()
            });
            // First-come-wins, exactly like the reference: the data is already
            // ordered best-first within a reading by the build step.
            if list.len() >= options.max_candidates_per_reading {
                continue;
            }
            list.push(Entry {
                word: word.to_string(),
                score,
                reading: reading.to_string(),
                syllables,
            });
            dict.size += 1;
            max_span = max_span.max(syllables);
        }

        // Stable sort by score descending: ties keep file order, matching
        // JavaScript's Array.prototype.sort.
        for list in dict.by_reading.values_mut() {
            list.sort_by(|a, b| b.score.total_cmp(&a.score));
        }
        dict.max_word_syllables = max_span.min(options.max_word_syllables);
        Ok(dict)
    }

    pub fn lookup(&self, reading: &str) -> &[Entry] {
        self.by_reading.get(reading).map(Vec::as_slice).unwrap_or(&[])
    }

    pub fn readings(&self) -> &[String] {
        &self.readings
    }

    pub fn size(&self) -> usize {
        self.size
    }

    pub fn max_word_syllables(&self) -> usize {
        self.max_word_syllables
    }
}

/// The set of legal syllables, derived from the dictionary rather than typed by
/// hand: a syllable is legal iff some word in the language model is read that way.
pub fn build_syllable_inventory(path: impl AsRef<Path>) -> std::io::Result<HashSet<String>> {
    let file = File::open(path)?;
    let mut set = HashSet::new();
    for line in BufReader::new(file).lines() {
        let line = line?;
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let Some((reading, _)) = line.split_once('\t') else { continue };
        for s in split_reading(reading) {
            set.insert(s.to_string());
        }
    }
    Ok(set)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn lm_path() -> std::path::PathBuf {
        Path::new(env!("CARGO_MANIFEST_DIR")).join("../data/bopomofo-lm.tsv")
    }

    #[test]
    fn loads_the_shipped_language_model() {
        let dict = Dictionary::load(lm_path()).unwrap();
        assert!(dict.size() > 100_000, "expected >100k entries, got {}", dict.size());
        assert_eq!(dict.lookup("ㄋㄧˇ-ㄏㄠˇ")[0].word, "你好");
        assert_eq!(dict.lookup("ㄨㄛˇ-ㄞˋ-ㄋㄧˇ")[0].score, -5.398);
    }

    #[test]
    fn inventory_matches_the_reference_count() {
        let inv = build_syllable_inventory(lm_path()).unwrap();
        assert_eq!(inv.len(), 1413, "the reference derives exactly 1,413 legal syllables");
    }
}
