#!/usr/bin/env node
/**
 * Build the browser demo from the *same* engine sources.
 *
 * No second implementation, no re-implementation drift: `module.stripTypeScriptTypes`
 * (Node 22.13+) turns the exact files the tests and benchmarks run against into
 * browser-loadable modules. The only edit is rewriting `./x.ts` specifiers to
 * `./x.js`, because browsers resolve extensions literally.
 *
 * This is also a small proof about the architecture: the decode pipeline has no
 * Node dependency at all, which is the same property the Rust core and the four
 * platform shells rely on.
 *
 * usage: node tools/build-demo.mjs
 */
import { stripTypeScriptTypes } from "node:module";
import { readFileSync, writeFileSync, mkdirSync, rmSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const engineSrc = join(here, "..", "engine", "src");
const outDir = join(here, "..", "demo", "engine");

/** Pure modules only — anything importing node:fs would break in a browser. */
const MODULES = [
  "syllable.ts",
  "keyboard.ts",
  "dictionary.ts",
  "grid.ts",
  "userdict.ts",
  "engine.ts",
];

rmSync(outDir, { recursive: true, force: true });
mkdirSync(outDir, { recursive: true });

let total = 0;
for (const name of MODULES) {
  const source = readFileSync(join(engineSrc, name), "utf8");
  if (/from\s+"node:/.test(source)) {
    throw new Error(`${name} imports a Node built-in; it cannot run in a browser`);
  }
  const stripped = stripTypeScriptTypes(source, { mode: "strip" });
  const browserReady = stripped.replace(/(from\s+"\.\/[^"]+)\.ts"/g, '$1.js"');
  const out = join(outDir, name.replace(/\.ts$/, ".js"));
  writeFileSync(out, browserReady);
  total += browserReady.length;
  process.stdout.write(`  ${name} -> demo/engine/${name.replace(/\.ts$/, ".js")} (${browserReady.length} B)\n`);
}

writeFileSync(
  join(outDir, "BUILD-INFO.txt"),
  `Generated by tools/build-demo.mjs from engine/src/. Do not edit.\n` +
    `These are the exact modules the test suite runs against, with TypeScript\n` +
    `syntax stripped by Node's own parser.\n`,
);
process.stdout.write(`total ${total} B\n`);
