/**
 * Dictionary / language model.
 *
 * Data comes from data/bopomofo-lm.tsv, generated by data/build.mjs from
 * McBopomofo's MIT-licensed WebData. Each row is
 *     reading<TAB>word<TAB>log10_probability
 * where the reading is a '-' joined sequence of composed bopomofo syllables.
 */
import { splitReading } from "./syllable.ts";

export interface Entry {
  word: string;
  score: number;
  reading: string;
  /** number of syllables the word spans */
  syllables: number;
}

export interface DictionaryOptions {
  /** hard cap on how many syllables one dictionary word may cover */
  maxWordSyllables?: number;
  /** keep at most this many candidates per reading */
  maxCandidatesPerReading?: number;
}

export class Dictionary {
  private readonly byReading = new Map<string, Entry[]>();
  readonly readings: string[] = [];
  maxWordSyllables = 1;
  readonly source: string;

  private constructor(source: string) {
    this.source = source;
  }

  /**
   * Build from the compiled TSV *text*. The format is deliberately plain text:
   * it is the project's portable interchange format, so the Rust core, an ArkTS
   * shell and a browser page all read exactly the same bytes.
   *
   * Reading the file is the caller's job — `node-data.ts` does it for Node, and
   * a platform shell does it with whatever its own filesystem API is. Keeping
   * this function pure is what lets the very same module run in a browser.
   */
  static fromText(text: string, source = "<text>", options: DictionaryOptions = {}): Dictionary {
    const maxCandidates = options.maxCandidatesPerReading ?? 128;
    const dict = new Dictionary(source);
    let maxSpan = 1;
    for (const line of text.split("\n")) {
      if (!line || line.startsWith("#")) continue;
      const first = line.indexOf("\t");
      const second = line.indexOf("\t", first + 1);
      if (first < 0 || second < 0) continue;
      const reading = line.slice(0, first);
      const word = line.slice(first + 1, second);
      const score = Number.parseFloat(line.slice(second + 1));
      if (!reading || !word || !Number.isFinite(score)) continue;
      const syllables = splitReading(reading).length;
      let list = dict.byReading.get(reading);
      if (!list) {
        list = [];
        dict.byReading.set(reading, list);
        dict.readings.push(reading);
      }
      if (list.length >= maxCandidates) continue;
      list.push({ word, score, reading, syllables });
      if (syllables > maxSpan) maxSpan = syllables;
    }
    for (const list of dict.byReading.values()) list.sort((a, b) => b.score - a.score);
    dict.maxWordSyllables = Math.min(maxSpan, options.maxWordSyllables ?? 10);
    return dict;
  }

  /** All known words for one reading, best first. */
  lookup(reading: string): Entry[] {
    return this.byReading.get(reading) ?? [];
  }

  get size(): number {
    let n = 0;
    for (const list of this.byReading.values()) n += list.length;
    return n;
  }
}

/**
 * The set of legal syllables, derived from the dictionary rather than typed by
 * hand: a syllable is legal iff some word in the language model is read that way.
 */
export function buildSyllableInventoryFromText(text: string): Set<string> {
  const set = new Set<string>();
  for (const line of text.split("\n")) {
    if (!line || line.startsWith("#")) continue;
    const tab = line.indexOf("\t");
    if (tab < 0) continue;
    for (const s of splitReading(line.slice(0, tab))) set.add(s);
  }
  return set;
}
